services:
  - type: web
    name: personal-assistant-homepage
    runtime: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./out
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
