import type { Metadata } from "next";
import Link from "next/link";
import LegalHero from "@/components/LegalHero";
import { site } from "@/lib/site";

export const metadata: Metadata = {
  title: "Data Deletion Instructions",
  description: `How to revoke ${site.productName}'s access to your Google Account and request deletion of your data.`,
};

const h2 = "mt-10 text-xl font-bold text-foreground sm:text-2xl";
const p = "mt-3 text-[15px] leading-relaxed text-foreground/70";
const ul = "mt-3 list-disc space-y-2 pl-5 text-[15px] leading-relaxed text-foreground/70";
const ol = "mt-3 list-decimal space-y-2 pl-5 text-[15px] leading-relaxed text-foreground/70";

export default function DataDeletionPage() {
  return (
    <>
      <LegalHero title="Data Deletion Instructions" updated="July 17, 2026" />

      <div className="mx-auto max-w-3xl px-5 py-14 sm:px-8">
        <p className={p}>
          You remain in control of your data at all times. This page explains how to revoke{" "}
          <strong>{site.productName}</strong>&apos;s access to your Google Account and how to
          request deletion of any data the Application has stored.
        </p>

        <h2 className={h2}>1. Revoke Google Account Access</h2>
        <p className={p}>
          Revoking access immediately stops {site.productName} from accessing your Gmail,
          Google Calendar, and Google Contacts data:
        </p>
        <ol className={ol}>
          <li>
            Go to your{" "}
            <a
              href="https://myaccount.google.com/permissions"
              target="_blank"
              rel="noopener noreferrer"
              className="font-medium text-brand-600 hover:text-brand-700"
            >
              Google Account permissions page
            </a>
            .
          </li>
          <li>Find <strong>{site.productName}</strong> in the list of third-party apps with account access.</li>
          <li>Select it and click <strong>Remove Access</strong>.</li>
        </ol>

        <h2 className={h2}>2. Request Deletion of Stored Data</h2>
        <p className={p}>
          To have all data associated with your account deleted from our systems (such as
          cached summaries and authentication tokens), send a deletion request to{" "}
          <a href={`mailto:${site.supportEmail}`} className="font-medium text-brand-600 hover:text-brand-700">
            {site.supportEmail}
          </a>{" "}
          from the Google Account email address you used to sign in, with the subject line
          &ldquo;Data Deletion Request.&rdquo;
        </p>
        <p className={p}>
          We will confirm and complete the deletion within 30 days of receiving your request,
          except where retention is required by law.
        </p>

        <h2 className={h2}>3. What Gets Deleted</h2>
        <ul className={ul}>
          <li>Authentication tokens linking {site.productName} to your Google Account.</li>
          <li>Cached email summaries, drafts metadata, and scheduling data generated by the Application.</li>
          <li>Your account profile information (name, email address, profile picture).</li>
        </ul>
        <p className={p}>
          Deletion of data stored by {site.productName} does not affect your emails, calendar
          events, or contacts in your Google Account itself — those remain untouched in your
          Google services.
        </p>

        <h2 className={h2}>4. Questions</h2>
        <p className={p}>
          If you have questions about data deletion or our data practices, contact{" "}
          {site.developer} at{" "}
          <a href={`mailto:${site.supportEmail}`} className="font-medium text-brand-600 hover:text-brand-700">
            {site.supportEmail}
          </a>
          . See also our{" "}
          <Link href="/privacy" className="font-medium text-brand-600 hover:text-brand-700">
            Privacy Policy
          </Link>{" "}
          and{" "}
          <Link href="/terms" className="font-medium text-brand-600 hover:text-brand-700">
            Terms of Service
          </Link>
          .
        </p>
      </div>
    </>
  );
}
